Explicitly install lua-ev with luarocks, as it seems that sometimes it is not installed...

diff --git a/bin/build-client b/bin/build-client
--- a/bin/build-client
+++ b/bin/build-client
@@ -24,15 +24,20 @@ git submodule update
   ) >> "${cosy_log}" 2>&1 \
     && echo -e "${green}success${nc}" \
     || echo -e "${red}failure${nc}"
-  echo -n "Installing cosy... "
-  { ${sudo} "${cosy_prefix}/bin/luarocks" make rockspec/cosy-client-master-1.rockspec \
-      LIBEV_DIR="${cosy_prefix}"
-  } >> "${cosy_log}" 2>&1 \
+  echo -n "  Installing lua-ev..."
+  ( ${sudo} "${cosy_prefix}/bin/luarocks" install lua-ev
+  ) >> "${cosy_log}" 2>&1 \
     && echo -e "${green}success${nc}" \
     || echo -e "${red}failure${nc}"
   echo -n "  Installing luasocket (dev version)..."
   ( ${sudo} "${cosy_prefix}/bin/luarocks" install --server=https://luarocks.org/dev luasocket
   ) >> "${cosy_log}" 2>&1 \
+    && echo -e "${green}success${nc}" \
+    || echo -e "${red}failure${nc}"
+  echo -n "Installing cosy... "
+  { ${sudo} "${cosy_prefix}/bin/luarocks" make rockspec/cosy-client-master-1.rockspec \
+      LIBEV_DIR="${cosy_prefix}"
+  } >> "${cosy_log}" 2>&1 \
     && echo -e "${green}success${nc}" \
     || echo -e "${red}failure${nc}"
 }
diff --git a/bin/build-server b/bin/build-server
--- a/bin/build-server
+++ b/bin/build-server
@@ -22,23 +22,27 @@ git submodule update
   ) >> "${cosy_log}" 2>&1 \
     && echo -e "${green}success${nc}" \
     || echo -e "${red}failure${nc}"
-  echo -n "Installing cosy... "
-  ( ${sudo} "${cosy_prefix}/bin/luarocks" make rockspec/cosy-client-master-1.rockspec \
-      LIBEV_DIR="${cosy_prefix}"
-    ${sudo} "${cosy_prefix}/bin/luarocks" make rockspec/cosy-master-1.rockspec \
-      LIBEV_DIR="${cosy_prefix}"
+  echo -n "  Installing lua-ev..."
+  ( ${sudo} "${cosy_prefix}/bin/luarocks" install lua-ev
   ) >> "${cosy_log}" 2>&1 \
     && echo -e "${green}success${nc}" \
     || echo -e "${red}failure${nc}"
   echo -n "  Installing luasocket (dev version)..."
-  ( cd redis-lua
-    ${sudo} "${cosy_prefix}/bin/luarocks" install --server=https://luarocks.org/dev luasocket
+  ( ${sudo} "${cosy_prefix}/bin/luarocks" install --server=https://luarocks.org/dev luasocket
   ) >> "${cosy_log}" 2>&1 \
     && echo -e "${green}success${nc}" \
     || echo -e "${red}failure${nc}"
   echo -n "  Installing redis-lua (patched for cosy)... "
   ( cd redis-lua
     ${sudo} "${cosy_prefix}/bin/luarocks" make rockspec/redis-lua-scm-1.rockspec
+  ) >> "${cosy_log}" 2>&1 \
+    && echo -e "${green}success${nc}" \
+    || echo -e "${red}failure${nc}"
+  echo -n "Installing cosy... "
+  ( ${sudo} "${cosy_prefix}/bin/luarocks" make rockspec/cosy-client-master-1.rockspec \
+      LIBEV_DIR="${cosy_prefix}"
+    ${sudo} "${cosy_prefix}/bin/luarocks" make rockspec/cosy-master-1.rockspec \
+      LIBEV_DIR="${cosy_prefix}"
   ) >> "${cosy_log}" 2>&1 \
     && echo -e "${green}success${nc}" \
     || echo -e "${red}failure${nc}"
