Update build scripts for Lua 5.2.

diff --git a/bin/build-client b/bin/build-client
--- a/bin/build-client
+++ b/bin/build-client
@@ -27,11 +27,6 @@ else
   nc='\033[0m'
 fi
 
-## Now cmd args have been parsed
-##################################
-
-parallel=1
-
 # Useful variables:
 cosy_temp=$(mktemp -d 2>/dev/null || mktemp -d -t cosy)
 cosy_prefix="${cosy_temp}/usr"
@@ -41,7 +36,6 @@ cosy_bin_cli="${cosy_prefix}/bin/cosy"
 cosy_rockstree="${cosy_prefix}/local/cosy"
 cosy_log="${cosy_temp}/install.log"
 cosy_dependencies=(
-  luasec
   ansicolors
   argparse
   copas
@@ -53,6 +47,7 @@ cosy_dependencies=(
   luafilesystem
   luaposix
   luasocket
+  luasec
   lustache
 )
 
@@ -101,47 +96,48 @@ function install_dependencies ()
   export LD_LIBRARY_PATH="${cosy_prefix}/lib:${LD_LIBRARY_PATH}"
 }
 
-# Install LuaJIT with 5.2 compatibility:
-function install_luajit ()
+function install_lua ()
 {
-  echo "Installing luajit."
+  echo "Installing lua."
   (
-    cd luajit || exit 1
-    cat > "${cosy_temp}/luajit.patch" <<EOL
-diff -rupN LuaJIT-2.0.4.back/Makefile LuaJIT-2.0.4/Makefile
---- LuaJIT-2.0.4.back/Makefile	2015-10-02 17:19:16.774268017 +0200
-+++ LuaJIT-2.0.4/Makefile	2015-10-02 17:11:14.533865635 +0200
-@@ -24,7 +24,7 @@ ABIVER=  5.1
- # Change the installation path as needed. This automatically adjusts
- # the paths in src/luaconf.h, too. Note: PREFIX must be an absolute path!
- #
--export PREFIX= /usr/local
-+export PREFIX= ${cosy_rockstree}
- export MULTILIB= lib
- ##############################################################################
-
-diff -rupN LuaJIT-2.0.4.back/src/Makefile LuaJIT-2.0.4/src/Makefile
---- LuaJIT-2.0.4.back/src/Makefile	2015-10-02 17:19:06.294172164 +0200
-+++ LuaJIT-2.0.4/src/Makefile	2015-10-02 17:18:50.882031189 +0200
-@@ -100,7 +100,7 @@ XCFLAGS=
- # enabled by default. Some other features that *might* break some existing
- # code (e.g. __pairs or os.execute() return values) can be enabled here.
- # Note: this does not provide full compatibility with Lua 5.2 at this time.
--#XCFLAGS+= -DLUAJIT_ENABLE_LUA52COMPAT
-+XCFLAGS+= -DLUAJIT_ENABLE_LUA52COMPAT
- #
- # Disable the JIT compiler, i.e. turn LuaJIT into a pure interpreter.
- #XCFLAGS+= -DLUAJIT_DISABLE_JIT
+    cd lua || exit 1
+    cat > "${cosy_temp}/lua.patch" <<EOL
+--- Makefile.back	2015-12-22 09:51:51.000000000 +0100
++++ Makefile	2015-12-22 09:52:26.000000000 +0100
+@@ -10,7 +10,7 @@
+ # so take care if INSTALL_TOP is not an absolute path. See the local target.
+ # You may want to make INSTALL_LMOD and INSTALL_CMOD consistent with
+ # LUA_ROOT, LUA_LDIR, and LUA_CDIR in luaconf.h.
+-INSTALL_TOP= /usr/local
++INSTALL_TOP= ${cosy_rockstree}
+ INSTALL_BIN= \$(INSTALL_TOP)/bin
+ INSTALL_INC= \$(INSTALL_TOP)/include
+ INSTALL_LIB= \$(INSTALL_TOP)/lib
 EOL
-    patch -p1 -i "${cosy_temp}/luajit.patch"
-    make -j"${parallel}"
+    patch -i "${cosy_temp}/lua.patch" Makefile
+    case "$(uname -s)" in
+      "Linux")
+        make linux -j"${parallel}"
+        ;;
+      "Darwin")
+        make macosx -j"${parallel}"
+        ;;
+      *)
+        echo -e "Error: unknown OS: ${red}$(uname -s)${nc}."
+        exit 1
+        ;;
+    esac >> "${cosy_log}" 2>&1
     make install CC="clang"
     make clean
     git checkout Makefile
-    git checkout src/Makefile
-    ln -sf "luajit-2.1.0-beta1" "${cosy_rockstree}/bin/luajit"
-    ln -sf "luajit-2.1"         "${cosy_rockstree}/include/luajit-2.0"
   ) >> "${cosy_log}" 2>&1
+  {
+    lua_version=$("${cosy_rockstree}/bin/lua" -e 'print (_VERSION:match "Lua%s+(%d%.%d).*")')
+    lua_sversion=${lua_version//./}
+    ln -sF "lua"       "${cosy_rockstree}/bin/lua${lua_sversion}"
+    ln -sF "lua.h"     "${cosy_rockstree}/include/lua${lua_sversion}.h"
+    ln -sF "liblua.a"  "${cosy_rockstree}/lib/liblua${lua_sversion}.a"
+  } >> "${cosy_log}" 2>&1
 }
 
 function install_luarocks ()
@@ -151,10 +147,8 @@ function install_luarocks ()
     cd luarocks || exit 1
     export PATH="${cosy_rockstree}/bin:${PATH}"
     ./configure --prefix="${cosy_rockstree}" \
-                --lua-version="5.1" \
-                --lua-suffix="jit" \
                 --with-lua-bin="${cosy_rockstree}/bin/" \
-                --with-lua-include="${cosy_rockstree}/include/luajit-2.0/" \
+                --with-lua-include="${cosy_rockstree}/include/" \
                 --with-lua-lib="${cosy_rockstree}/lib/"
     make bootstrap
     make clean
@@ -166,34 +160,34 @@ function install_cosyverif ()
 {
   echo "Installing rocks."
   # Remove symlink to cosy to avoid modification of sources files by luarocks:
-  rm -rf "${cosy_rockstree}/share/lua/5.1/redis.lua"
-  rm -rf "${cosy_rockstree}/share/lua/5.1/cosy"
+  rm -rf "${cosy_rockstree}/share/lua/${lua_version}/redis.lua"
+  rm -rf "${cosy_rockstree}/share/lua/${lua_version}/cosy"
   # Install luasec before everything to allow the use of HTTPS in luarocks:
-  options=(
-    LUA="${cosy_rockstree}/bin/luajit"
-  )
-  more_dependencies=()
   export CC=clang
-  for dependency in ${cosy_dependencies[*]} ${more_dependencies[*]}; do
+  for dependency in luasec ${cosy_dependencies[*]}; do
     if "${cosy_rockstree}/bin/luarocks" list \
         --porcelain \
         --tree="${cosy_rockstree}" \
         | grep --silent "${dependency}"; then
       echo "  Not installing ${dependency} as it is already installed."
     else
-      echo "  Installing ${dependency} as it is not installed."
+      echo -n "  Installing ${dependency} as it is not installed... "
       # shellcheck disable=SC2086
-      "${cosy_rockstree}/bin/luarocks" install "${dependency}" ${options[*]} \
-          >> "${cosy_log}" 2>&1
+      if "${cosy_rockstree}/bin/luarocks" install "${dependency}" \
+          >> "${cosy_log}" 2>&1; then
+        echo -e "${green}success${nc}"
+      else
+        echo -e "${red}failure${nc}"
+      fi
     fi
   done
-  # Create symlinks in rockstree:
-  rm -rf "${cosy_rockstree}/share/lua/5.1/redis.lua"
+  # Copy in rockstree:
+  rm -rf "${cosy_rockstree}/share/lua/${lua_version}/redis.lua"
   cp     "redis-lua/src/redis.lua" \
-         "${cosy_rockstree}/share/lua/5.1/redis.lua"
-  rm -rf "${cosy_rockstree}/share/lua/5.1/cosy"
+         "${cosy_rockstree}/share/lua/${lua_version}/redis.lua"
+  rm -rf "${cosy_rockstree}/share/lua/${lua_version}/cosy"
   cp -r  "src/cosy" \
-         "${cosy_rockstree}/share/lua/5.1/cosy"
+         "${cosy_rockstree}/share/lua/${lua_version}/cosy"
 }
 
 function install_bin ()
@@ -202,7 +196,7 @@ function install_bin ()
   cat > "${cosy_bin_path}" <<EOF
 #! /bin/bash
 
-$(cat "sh-realpath/realpath.sh" | grep -v "#!")
+$(grep -v "#!" < "sh-realpath/realpath.sh")
 
 cosy_where=\$(realpath "\${BASH_SOURCE}")
 cosy_where=\$(dirname  "\${cosy_where}")
@@ -210,8 +204,12 @@ cosy_where=\$(dirname  "\${cosy_where}")
 export COSY_PREFIX="\${cosy_where}"
 
 export PATH="\${COSY_PREFIX}/bin:\${COSY_PREFIX}/local/cosy/bin:\${PATH}"
-export LUA_PATH="\${COSY_PREFIX}/local/cosy/share/lua/5.1/?.lua;\${COSY_PREFIX}/local/cosy/share/lua/5.1/?/init.lua"
-export LUA_CPATH="\${COSY_PREFIX}/local/cosy/lib/lua/5.1/?.so"
+
+lua_version=\$(lua -e 'print (_VERSION:match "Lua%s+(%d%.%d).*")')
+lua_sversion=\${lua_version//./}
+
+export LUA_PATH="\${COSY_PREFIX}/local/cosy/share/lua/\${lua_version}/?.lua;\${COSY_PREFIX}/local/cosy/share/lua/\${lua_version}/?/init.lua"
+export LUA_CPATH="\${COSY_PREFIX}/local/cosy/lib/lua/\${lua_version}/?.so"
 
 export LIBRARY_PATH="\${COSY_PREFIX}/lib:${LIBRARY_PATH}"
 export LD_LIBRARY_PATH="\${COSY_PREFIX}/lib:${LD_LIBRARY_PATH}"
@@ -232,7 +230,7 @@ EOF
 root=\$(dirname "\$0")
 # shellcheck source=/dev/null
 source "\${root}/${base}"
-luajit "\${COSY_PREFIX}/local/cosy/share/lua/5.1/cosy/cli/init.lua" "\$@"
+\$(lua -e "print (package.searchpath ('cosy.cli', package.path))") "\$@"
 EOF
   chmod a+x "${cosy_bin_cli}"
 }
@@ -289,7 +287,7 @@ mkdir -p "${cosy_prefix}/bin"
 mkdir -p "${cosy_prefix}/lib"
 trap error ERR
 install_dependencies
-install_luajit
+install_lua
 install_luarocks
 install_cosyverif
 install_bin
