Install latest dev version of luasocket in build scripts, as there is a problem with copas.http otherwise.

diff --git a/bin/build-server b/bin/build-server
--- a/bin/build-server
+++ b/bin/build-server
@@ -140,12 +140,6 @@ function install_lua () {
        || echo -e "${red}failure${nc}"
     fi
   done
-  echo -n "  Installing redis-lua (patched for cosy)... "
-  ( cd redis-lua
-    "${cosy_prefix}/bin/luarocks" make rockspec/redis-lua-scm-1.rockspec
-  ) >> "${cosy_log}" 2>&1 \
-    && echo -e "${green}success${nc}" \
-    || echo -e "${red}failure${nc}"
   echo -n "Installing lua 5.1 and luarocks for nginx... "
   hererocks "${cosy_temp}/lua_install" -r^ --lua="5.1" \
     >> "${cosy_log}" 2>&1 \
@@ -190,6 +184,18 @@ function install_lua () {
     rm -rf "${cosy_prefix}/share/lua/${lua_version}/cosy"
     ln -s  "${PWD}/src/cosy" \
            "${cosy_prefix}/share/lua/${lua_version}/cosy"
+  ) >> "${cosy_log}" 2>&1 \
+    && echo -e "${green}success${nc}" \
+    || echo -e "${red}failure${nc}"
+  echo -n "  Installing luasocket dev version..."
+  ( cd redis-lua
+    "${cosy_prefix}/bin/luarocks" install --server=https://luarocks.org/dev luasocket
+  ) >> "${cosy_log}" 2>&1 \
+    && echo -e "${green}success${nc}" \
+    || echo -e "${red}failure${nc}"
+  echo -n "  Installing redis-lua (patched for cosy)... "
+  ( cd redis-lua
+    "${cosy_prefix}/bin/luarocks" make rockspec/redis-lua-scm-1.rockspec
   ) >> "${cosy_log}" 2>&1 \
     && echo -e "${green}success${nc}" \
     || echo -e "${red}failure${nc}"
