Prepare bin/setup for inclusion in nginx.

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -18,18 +18,17 @@ nc='\033[0m'
 tempwd=$(mktemp -d)
 log=$(mktemp)
 
-
 for i in "$@"
 do
   case ${i} in
-    -f=*|--full_uri=*)
-      pkg_uri="${i#*=}"
-      pkg_uri=${pkg_uri%/}
+    -f=*|--package-uri=*)
+      package_uri="${i#*=}"
+      package_uri=${package_uri%/}
       shift # past argument=value
     ;;
-    -r=*|--root_uri=*)
-      cosy_server_uri="${i#*=}"
-      cosy_server_uri=${sourcepath%/}
+    -r=*|--root-uri=*)
+      root_uri="${i#*=}"
+      root_uri=${root_uri%/}
       shift # past argument=value
     ;;
     -p=*|--prefix=*)
@@ -39,131 +38,90 @@ do
     ;;
     -h|--help)
       echo "Usage: "
-      echo "  install [--prefix=PREFIX] [--root_uri=<http://cosy>] [--full_uri=<http://cosy/pkg_v_os_arch.tar.gz>]"
+      echo "  install [--prefix=PREFIX] [--root-uri=<URI> | --package-uri=<URI>]"
       exit 1;
     ;;
     *)
-      echo "Usage: "
-      echo "  install [--prefix=PREFIX] [--root_uri=<http://cosy>] [--full_uri=<http://cosy/pkg_v_os_arch.tar.gz>]"
-      exit 1;
+    echo "Usage: "
+    echo "  install [--prefix=PREFIX] [--root-uri=<URI> | --package-uri=<URI>]"
+    exit 1;
       # unknown option
     ;;
   esac
 done
 
+prefix=${prefix:-"/usr/local/"}
 
-
-scriptname=$0
-parentdir="${prefix}"
-#basedir=$(basename "${prefix}")
-
-cosyname="cosycli"
-cosyversion="0.2"
-
-### compute default packg name automatically depending on OS arch
-packg="${cosyname}_${cosyversion}_"$(uname -m)_$(uname -o | sed -e 's/ /_/g' | sed -e 's/\//_/g')".tar.gz"
-if [ ! -z "${pkg_uri}" ]; then
-  ## override default package name
-  packg=$(basename "${pkg_uri}")
-elif [ ! -z "${cosy_server_uri}" ]; then
-  ##  use provided uri  with  default package name
-  pkg_uri=${cosy_server_uri}/${packg}
-else
-  ##  use default uri  with  default package name
-  cosy_server_uri="http://public.cosyverif.fr"
-  pkg_uri=${cosy_server_uri}/${packg}
+if [ ! -z "${root_uri}" ] && [ ! -z "${package_uri}" ]; then
+  echo -e "${red}Error: cannot set both '--root-uri' and '--package-uri'.${nc}"
+  exit 1
+elif [ -z "${root_uri}" ] && [ -z "${package_uri}" ]; then
+  root_uri="http://127.0.0.1:8080"
 fi
 
+if [ ! -z "${root_uri}" ]; then
+  os="  $(uname -o | sed -e 's/ /_/g' | sed -e 's/\//_/g' | tr '[:upper:]' '[:lower:]')"
+  arch="$(uname -m | sed -e 's/ /_/g' | sed -e 's/\//_/g' | tr '[:upper:]' '[:lower:]')"
+  package_uri="${root_uri}/setup/${arch}/${os}/client.tar.gz"
+fi
 
-
-echo -e "Script name        :  ${green}${scriptname}${nc}"
 echo -e "Temporary directory: ${green}${tempwd}${nc}"
-echo -e "Log file           :  ${green}${log}${nc}"
-echo -e "Prefix             :  ${green}${prefix}${nc}"
-echo -e "Parentdir          :  ${green}${parentdir}${nc}"
-#echo -e "Basedir            :  ${green}${basedir}${nc}"
-#echo -e "Cosyname           :  ${green}${cosyname}${nc}"
-#echo -e "Cosyversion        :  ${green}${cosyversion}${nc}"
-echo -e "Cosy_server_uri    :  ${green}${cosy_server_uri}${nc}"
-echo -e "Packg              :  ${green}${packg}${nc}"
-echo -e "Pkg_uri            :  ${green}${pkg_uri}${nc}"
+echo -e "Log file           : ${green}${log}${nc}"
+echo -e "Prefix             : ${green}${prefix}${nc}"
+echo -e "Package URI        : ${green}${package_uri}${nc}"
 
+cd "${tempwd}"
 
-
-
-
-
-
-## assert the curl is available 
-## assert the target dir exists or make it 
-## test if the target dir exists
-function install_package ()
+function download ()
 {
-  echo "Installing the package."
-  (
-    ## assert the target dir exists or make it 
-    if [ ! -d "${parentdir}" ]; then
-      mkdir -p "${parentdir}"
-      if [ ! -d "${parentdir}" ]; then
-        echo "Fatal: directory ${parentdir} is not reachable"
-        exit 1;
-      fi
-    fi
-    #t# fetch the archive
-    echo "inside $(pwd)"
-    echo "::: cd ${tempwd}"
-    cd "${tempwd}"
-    echo "inside $(pwd)"
-    
-
-    # check if curl is available:
+  echo -e "Downloading package ${green}${package_uri}${nc}."
+  {
     if command -v curl; then
-      #curl_available=true
-      curl --location --silent -O "${pkg_uri}"
+      curl --location --output "client.tar.gz" "${package_uri}"
+      return
     elif command -v wget; then
-      #wget_available=true
-      wget --quiet -O "${pkg_uri}"
-    else
-      echo "Neither curl nor wget is available."
-      exit 1;
-    fi >> "${log}" 2>&1
-    ## check got packg
-    if [ ! -f "${packg}" ]; then
-      echo "Missing file : ${packg}."
-      echo " from uri : ${pkg_uri}."
-      exit 1;
-    fi >> "${log}" 2>&1
+      wget --output-document="client.tar.gz" "${package_uri}"
+      return
+    fi
+  } >> "${log}" 2>&1
+  echo -e "${red}Error: neither curl nor wget is available.${nc}"
+  exit 1;
+}
 
+function install ()
+{
+  echo -e "Installing package to ${green}${prefix}${nc}."
+  {
+    mkdir -p "${prefix}"
+    tar xf  "client.tar.gz" \
+            --preserve-permissions \
+            --strip-components=1 \
+            --directory "${prefix}"
+  } >> "${log}" 2>&1
+}
 
-    # TODO check if directory would be erased
-    echo "inside $(pwd)"
-    echo "packg : ${packg}"
-    ls -al
-    ls -al "${packg}"
-
-    # check if tar is available:
-    if command -v tar; then
-      #tar_available=true
-      tar xf "${packg}"  --preserve-permissions --directory "${parentdir}"  
-    else
-      echo "Command tar is not available."
-      exit 1;
-    fi >> "${log}" 2>&1
-  ) >> "${log}" 2>&1
-
+function fix ()
+{
+  echo -e "Fixing COSY_PREFIX in ${green}${prefix}/bin/cosy-path${nc}."
+  sed -i  "s|export COSY_PREFIX=.*|export COSY_PREFIX=\"${prefix}\"|" \
+          "${prefix}/bin/cosy-path" \
+          >> "${log}" 2>&1
 }
 
 function error ()
 {
   echo -e "${red}An error happened.${nc}"
   echo -e "Please read log file: ${red}${log}${nc}."
-  if [ ! -z "${in_ci+x}" ]; then
-    cat "${log}"
-  fi
+  cat "${log}"
   exit 1
 }
 
+trap error ERR
+download
+install
+fix
 
-install_package
-echo "--------logs:---"
-cat "${log}"
+echo "You can now try the following commands:"
+echo "- ${prefix}/bin/cosy            : to run the cosy client"
+echo "- ${prefix}/bin/cosy-version    : to get version number"
+echo "- ${prefix}/bin/cosy-uninstall  : to uninstall cosy"
